### ISSUE TITLE
Incorrect pin names on Beaglebone P8 of Kicad schematic symbol

### ISSUE THREAD

**Issue by emeb** [piranha32/FlyingBone#1]
Pins B4 and B6 on unit C of the Kicad symbol for the Beaglebone are incorrectly labeled. The are shown as:

B4 = VDD_3V3EXP
B6 = VDD_5V

They should be

B4 = GPIO1_7
B6 = GPIO1_3

**Comment by piranha32** [comment]
Fixed.
