### ISSUE TITLE
Cape Schematic not visible when using lib

### ISSUE THREAD

**Issue by geros** [piranha32/FlyingBone#2]
Hi
I insert the .livb in my kicad libraries but when i insert it in me schematic i only get a battery.
Is there something wrong i am doing ?
Thnak you.

**Comment by piranha32** [comment]
Copying the file to the directory with kicad libraries may not be sufficient. In the project definition in github the library is located in lib directory in the main folder. If you kept the default directory structure it would have work just fine. If you want to have the library in a different location, please go to "Preferences->Library" and add the library to the project with "Add" button next to the list of active libraries (top part of the window).

**Comment by geros** [comment]
If i open the project with the default dir structure it is true that there is no problem . 
I thought i could use the beaglebone defined in .lib just importing it from lib folder.
Thank you piranha32

**Comment by piranha32** [comment]
You can use the library, just add it to your project. KiCad unfortunately doesn't have a user-accessible list of "system" libraries which are active for all projects. You can hack the installation by modifying the system-defined list of libraries, but I don't recommend to do it. It will be a great PITA every time you want to install an update. It's much easier just to add the lib to each new project. I also recommend to keep all local libraries in a separate folder, somewhere around your home directory and keep the folder with system libraries as it came with the installation.

**Comment by geros** [comment]
Thanks for your advice.
