### ISSUE TITLE
Cape headers in offset location?

### ISSUE THREAD

**Issue by chmorgan** [piranha32/FlyingBone#3]
Hello.

I was looking at creating a BBB cape using the FlyingBone as a starting point and I see that there is a BeagleBone part that has the holes/signal definitions and then another set of headers on the board that are offset inside of the existing headers. It looks like the BeagleBone part holes are at the correct location for a set of male headers to plug into the board but I wasn't sure what the purpose of the other set of headers was. It also seems like the parts that correspond to the male pins were missing and should be aligned with the outer BB part holes (if the board was to be built by someone with the male headers soldered in place).

Chris

**Comment by piranha32** [comment]
The other set of holes on FlyingBone are just holes to solder wires. Otherwise, with pass-through headers installed it would be difficult to connect the rest of the circuit on the board.

**Comment by chmorgan** [comment]
Oh. I wasn't being clear I think.

There are two connectors on the board immediately inside of the outer two
sets of rows. The outer sets of rows appear to be at the position where the
male pins would be mounted so the cape plugs into the bbb, unless I'm
mistaken. But there aren't any connectors there on the board so I'm not
sure how it would plug in. I'm basing that on a 1.8" space between the
inner pins on the bbb reference manual.

Chris

On Jun 29, 2013, at 11:48 AM, Jacek Radzikowski notifications@github.com
wrote:

The other set of holes on FlyingBone are just holes to solder wires.
Otherwise, with pass-through headers installed it would be difficult to
connect the rest of the circuit on the board.

—
Reply to this email directly or view it on
GitHubhttps://github.com/piranha32/FlyingBone/issues/3#issuecomment-20232060
.

**Comment by piranha32** [comment]
The outer set of holes is for the BB/BBB headers. The inner set of holes is to connect the signals to the circuit on the board. I'm not sure about what connections you are writing about. Each of the holes in the inner set is connected to the corresponding hole in the board connector. You don't have to mount any pins in the inner set. The holes are there only to help solder wires going to the rest of the circuit.

**Comment by chmorgan** [comment]
Oh ok. That's kind of what I was thinking.

I was wondering how I would add the male header pin rows to the location of
the outer pins in the schematic. That would make it more explicit as to
what part should be placed there. I just wasn't sure if the correct
approach was to add the male headers and put them there manually, lining
the holes/pins up by eye.

I'm used to the board having the headers, I was wondering why the bb
footprint was a separate part but figured it was to make it easier to
create new cape boards.

Chris

On Jun 29, 2013, at 12:22 PM, Jacek Radzikowski notifications@github.com
wrote:

The outer set of holes is for the BB/BBB headers. The inner set of holes is
to connect the signals to the circuit on the board. I'm not sure about what
connections you are writing about. Each of the holes in the inner set is
connected to the corresponding hole in the board connector. You don't have
to mount any pins in the inner set. The holes are there only to help solder
wires going to the rest of the circuit.

—
Reply to this email directly or view it on
GitHubhttps://github.com/piranha32/FlyingBone/issues/3#issuecomment-20232659
.

**Comment by piranha32** [comment]
The footprint is separate from FlyingBone and is a library component for use with your own projects.

**Comment by chmorgan** [comment]
Right.

So I can just add some male headers and line them up with the bb holes.

Interested in a bbb part? Some of the pins have been removed vs the bb. I
can push out a fork of the repo on github with a new bbb part copied from
bb with the removed pins removed.

Chris

**Comment by piranha32** [comment]
I updated the library with BBB part. Please let me know if find any problems.
