### ISSUE TITLE
beaglebone library

### ISSUE THREAD

**Issue by carycode** [piranha32/FlyingBone#4]
When I open up "FlyingBone.sch" in KiCad, I get this error: "Files not found: The following libraries could not be found: beaglebone".

Is there something wrong on my end, or is there a file missing in this project?

p.s.: Thank you very much for posting these cape design files online; I found them very useful. -- carycode

**Comment by piranha32** [comment]
Sorry, for delay, for some reason I did not get notification about comment.
Did you add beaglebone library to kicad?
